spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/world
    username: root
    password: xiaobing
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
